version: "2"
services:
    wordpress:
        build: .
        container_name: wp
        ports:
            - "9000:80"
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: "db:3306"
        env_file: .env
        volumes:
            - ./lp:/var/www/html/lp
            - ./vendor:/var/www/html/vendor
            - ./wp-content/themes/_s:/var/www/html/wp-content/themes/_s
            - ./wp-content/plugins:/var/www/html/wp-content/plugins
    db:
        image: mysql:latest
        env_file: .env
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
        driver: local
